# Docker Compose for stage1-chatbot: backend, frontend, and Ollama

services:
  ollama:
    image: docker.io/ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11435:11434"
    pull_policy: always
    tty: true
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend/system_prompt.txt:/app/system_prompt.txt:ro

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  ollama_data:
